[project]
name = "mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docformatter>=1.7.7",
    "lxml>=6.0.2",
    "markdownify>=1.2.0",
    "mcp[cli]>=1.14.1",
]

[dependency-groups]
dev = [
    "black>=25.9.0",
    "flake8>=7.3.0",
    "mypy>=1.18.2",
]

[tool.docformatter]
black = true
blank = false
close-quotes-on-newline = true

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 88
